baseURL=                    "https://b1101.github.io/"
languageCode=               "en-us"
title =                     "~b1101"
disqusShortname = "b1101"
googleAnalytics=            "UA-77952590-1"

editor=                     "nvim"
publishdir=                 "public"
pygmentsStyle=              "zenburn"

#theme:                     ""

[params]
subtitle = "Musician in the world of algorithms surrounded by a $SHELL"
copyright = "Romāns Volosatovs"
facebook = "https://facebook.com/r.volosatovs"
twitter = "https://twitter.com/flat1101"
linkedin = "https://www.linkedin.com/in/rvolosatovs"
github = "https://github.com/b1101"
analytics=            "UA-77952590-1"
showsRSS = true
#shareThis = "619e5085-8af7-4190-95a1-2e01d1b2e51a"
#profile = "/images/profile.png"
